cloudposse/charts

incubator/lamp/templates/_helpers.tpl
incubator/lamp/templates/ingress.yaml
incubator/nginx-default-backend/templates/configmap.yaml
incubator/nginx-default-backend/values.yaml
incubator/nginx-ingress/Chart.yaml
incubator/nginx-ingress/templates/configmap.yaml
incubator/nginx-ingress/values.yaml

* allow `custom-error-codes` to be defined in `values.yaml`
* some applications might already generate nice status pages
* other times we might want to intercept more status codes (e.g. `500` and `502`)
@goruha

Add support for defining custom HTTP error codes

---

incubator/postfix/templates/deployment.yaml
incubator/postfix/templates/secrets.yaml
incubator/postfix/values.yaml

* Update configuration to support relay host
* Secure relay to 3rd-party SMTP services like Mailgun or SES
* no need to expose provider credentials to internal apps (e.g. Wordpress) since they can be configured to use internal SMTP service
* Fault-tolerance - postfix will keep retrying until relay online

Add Support for Authenticated SMTP Relay Host

---

incubator/nginx-ingress/Chart.yaml
incubator/nginx-ingress/templates/configmap.yaml
incubator/nginx-ingress/templates/deployment.yaml
incubator/nginx-ingress/values.yaml

* Add support for `use-proxy-protocol`
* Make it configurable because  GCE LB does not support proxy protocol; If it is enabled on GCE - Ingress do not work.
* If you are using a L4 proxy to forward the traffic to the NGINX pods and terminate HTTP/HTTPS there, you will lose the remote endpoint's IP addresses. To prevent this you could use the Proxy Protocol for forwarding traffic, this will send the connection details before forwarding the actual TCP connection itself. 
* https://github.com/kubernetes/contrib/tree/99cba026d6c42d08b944aae1fd9fac173d76e3a1/ingress/controllers/nginx#proxy-protocol

Enable Support for `use-proxy-protocol`

---

incubator/alertmanager/Chart.yaml
incubator/alertmanager/templates/_alertmanager.yaml.tpl
incubator/alertmanager/templates/secret.yaml
incubator/prometheus/Chart.yaml
incubator/prometheus/templates/_configmaps.json.tpl
incubator/prometheus/templates/prometheus.yaml
incubator/prometheus/templates/rules.yaml
incubator/prometheus/templates/secret.yaml
incubator/prometheus/templates/servicemonitors.yaml
incubator/prometheus/values.yaml

* Made alertmanager config stored in secret
* Made prometheus config stored in secret
* Added support for prometheus rules selector
* Added support to override prometheus configs in umbrella chart with resource ( not by values )
* Added support to override prometheus rules in umbrella chart with resource ( not by values )
* Added support to specify custom selector for prometheus ServiceMonitors
* Added support to specify custom selector for prometheus rules configs
* Prometheus operator starting from version 0.7.0 use secrets to store configs
https://github.com/coreos/prometheus-operator/releases/tag/v0.7.0
* Provide flexible way to specify promethus config in umbrella chart resources (example you can find here #80 ). It is useful because configs sometimes required templating. Also …

Support Operator 0.7.0

---

incubator/prometheus/templates/prometheus.yaml

* Added default selector for Service Monitor
* Added default selector for Rules
* Default selectors useful for extend prometheus from external charts by defining Service Monitors and Rules

Added prometheus default selectors for rules and service Monitors

---

incubator/exporter-kube-state/.helmignore
incubator/exporter-kube-state/Chart.yaml
incubator/exporter-kube-state/templates/NOTES.txt
incubator/exporter-kube-state/templates/_helpers.tpl
incubator/exporter-kube-state/templates/configmap.yaml
incubator/exporter-kube-state/templates/deployment.yaml
incubator/exporter-kube-state/templates/service.yaml
incubator/exporter-kube-state/templates/servicemonitor.yaml
incubator/exporter-kube-state/values.yaml

* Created chart that provide prometheus exporter kube state and alerts for it

Added prometheus exporter kube state

---

incubator/kube-prometheus/requirements.yaml

* Revert back exporter-kube-state into kube-prometheus requirements
* exporter-kube-state is a part of end-to-end prometheus chart, and was removed from it's deps temporary. Now reverted back

Revert back exporter-kube-state into kube-prometheus deps

---

incubator/nginx-ingress/Chart.yaml
incubator/nginx-ingress/templates/deployment.yaml
incubator/nginx-ingress/values.yaml

* Update chart to use nginx ingress 0.9.0-beta.3
* Support multiple features like 3d party auth and annotations to config nginx

Update nginx ingress to version 0.9.0-beta.3

---

incubator/kube-prometheus/values.yaml
incubator/prometheus/values.yaml

* Added default resources limits to prometheus
* If resources not specify prometheus-operator request 2G and can grow. This makes crash of some small nodes in kubernetes cluster

Added default resource limits on prometheus

---

incubator/github-authorized-keys/Chart.yaml
incubator/github-authorized-keys/templates/daemonset.yaml

* Add master toleration
* We want `github-authorized-keys` deployed as a `DaemonSet` on *all* nodes, including master nodes
* With new versions of `kops` and `kubernetes`, by default pods are not scheduled on `master` nodes

Deploy Github Authorized Keys on All Nodes

---

incubator/lamp/Chart.yaml
incubator/lamp/requirements.yaml

* Bump new version `vps` chart in `lamp` chart deps
* Old version does not support new helm

Fix lamp bind new version vps

---

.travis.yml
Dockerfile
incubator/chartmuseum/.helmignore
incubator/chartmuseum/Chart.yaml
incubator/chartmuseum/OWNERS
incubator/chartmuseum/README.md
incubator/chartmuseum/requirements.yaml
incubator/chartmuseum/templates/NOTES.txt
incubator/chartmuseum/templates/deployment.yaml
incubator/chartmuseum/templates/ingress.yaml
incubator/chartmuseum/templates/pvc.yaml
incubator/chartmuseum/templates/secret.yaml
incubator/chartmuseum/templates/service.yaml
incubator/chartmuseum/values.yaml
incubator/kube-lego/values.yaml
incubator/kube2iam-kops/Chart.yaml
incubator/kube2iam-kops/requirements.yaml
incubator/kube2iam-kops/values.yaml
incubator/nginx-ingress/requirements.yaml
incubator/thumbor/requirements.yaml

* Chartmuseum chart
* Redo how we build helm serve docker image
* Bump versions for thumbor and nginx-ingress
* To build private chart repo
* Because of bug in new docker helm failed https://github.com/moby/moby/issues/22260
https://github.com/kubernetes/helm/blob/master/pkg/downloader/manager.go#L220
* Need to use new versions of charts with new helm
* Allow to upload charts
* Allow to serve charts
* Auto index based on files in directory
* Use aws s3 as storage
* Support ingress
* Support ingress annotations
* Support kube2iam annotations
* Support base http auth

Feature add chart museum

---

incubator/route53-kubernetes/Chart.yaml
incubator/route53-kubernetes/templates/daemonset.yaml

* Added tolerate 
* Allow to run pod on master

Feature route53 support kube2iam

---

incubator/chart-repo/README.md

* Depricate `incubator/chart-repo`
* Reduce count of custom charts

Depricate chart-repo

---

incubator/oauth2-proxy/Chart.yaml
incubator/oauth2-proxy/templates/configmap.yaml
incubator/oauth2-proxy/values.yaml

* Make oauth2 proxy pass to upstream headers `X-Auth-Request-User` and `X-Auth-Request-Email`
* To make auto creation users on upstream backends

Added config to pass x auth headers

---

incubator/thumbor/Chart.yaml
incubator/thumbor/templates/ingress.yaml
incubator/thumbor/values.yaml

* This change allows overriding the path mapped to the thumbor service in the charts values.
* For backwards compatibility I'm rendering the path in the template with `default` to ensure that old deploys that already configure ingress wont break on the update.
It makes it possible to host thumbor on the same domain as a single page application that expects thumbor to be at `/thumbor` instead of being on it's own domain.

[incubator/thumbor] allow overriding ingress path

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/daemonset.yaml
incubator/monochart/templates/deployment.yaml
incubator/monochart/templates/job.yaml
incubator/monochart/templates/pvc.yaml
incubator/monochart/templates/statefulset.yaml

This allows `values.yaml` to be simplified like:
```yaml
replicaCount: 1
image:
repository: rms1000watt/dummy-golang-project
tag: latest
pullPolicy: IfNotPresent
deployment:
enabled: true
service:
enabled: true
type: LoadBalancer
internalPort: 9999
externalPort: 80
```

added extra conditions so stubs are not required in values.yaml

---

incubator/thumbor/Chart.yaml
incubator/thumbor/templates/deployment.yaml
incubator/thumbor/values.yaml

* adds livenessProbe and readinessProbe
* name the container port "http" so it can be referenced by name
* make it easier to rollout changes to the thumbor install without downtime
* naming ports helps reference them in other places (like probes)
* Thumbor has some info on the `/healthcheck` endpoint in [their docs](https://github.com/thumbor/thumbor/wiki/Hosting#production-environment) and they recommend if for use behind a load balancer (and K8s Services are kinda loadbalancers).

[incubator/thumbor] add container probes

---

incubator/nginx-ingress/Chart.yaml
incubator/nginx-ingress/templates/configmap.yaml
incubator/nginx-ingress/templates/service.yaml
incubator/nginx-ingress/values.yaml

- Extends the usability of the chart by adding in conditionals for some of the more modern nginx-ingress features
- The big why here is making this chart usable when terminating SSL at an ELB. The [example](https://github.com/kubernetes/ingress-nginx/blob/master/deploy/provider/aws/service-l7.yaml) on the main repo shows that when terminating SSL at the ELB level, the target port for https rules should be the http port (specified as `http`, not `80`). 
- When terminating SSL at the ELB level, proxy protocol should be disabled, previously this chart had `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'` hard coded as a value, I implemented a minor change in the design of the chart to include this annotation in the service so long as use-proxy-protocol is set to `true` (it …

Extend usability of nginx-ingress chart

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/cronjob.yaml
incubator/monochart/templates/daemonset.yaml
incubator/monochart/templates/deployment.yaml
incubator/monochart/templates/ingress.yaml
incubator/monochart/templates/job.yaml
incubator/monochart/templates/service.yaml
incubator/monochart/templates/statefulset.yaml
incubator/monochart/values.yaml

* Support multiple jobs
* Support multiple cron jobs
* Standardize ingress declaration
* Make service select pods only from Deployment, Deamonset and Statefull Set
* Made service support multiple ports
* To have multiple jobs - for example `on install\update` and `on delete`
* To have multiple cron jobs
* To use the same way declare list of resources
* To solve problems when Service selects running jobs
* In case pods need several ports to be listen

[incubator/monochart] Support multiple cronjobs

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/cronjob.yaml
incubator/monochart/templates/daemonset.yaml
incubator/monochart/templates/deployment.yaml
incubator/monochart/templates/job.yaml
incubator/monochart/templates/statefulset.yaml
incubator/monochart/values.yaml

* Add `container.command` to monochart's `cronjob`, `daemonset`, `deployment`, `job` and `statefulset`
* To be able to override `ENTRYPOINT` from containers' Docker images
* Need to override `ENTRYPOINT` when, for example, deploying [`atlantis`](https://github.com/runatlantis/atlantis/blob/master/Dockerfile) and [`codefresh-cli`](https://github.com/codefresh-io/cli/blob/master/Dockerfile)
* https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/

[monochart] Add `container.command`

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/cronjob.yaml
incubator/monochart/templates/daemonset.yaml
incubator/monochart/templates/deployment.yaml
incubator/monochart/templates/job.yaml
incubator/monochart/templates/statefulset.yaml
incubator/monochart/values.yaml

* Added security context for pods
* Made persistent volume mount path configurable
* For some apps (ex.: openvpn) security context is required 
* Some apps does not allow you to config path for persistent storage, so chart should allow mount the volume any dir

[incubator/monochart] support security contexts and mount paths

---

incubator/monochart/Chart.yaml
incubator/monochart/LICENSE
incubator/monochart/templates/_helpers.tpl
incubator/monochart/templates/statefulset.yaml
incubator/monochart/values.example.yaml
incubator/monochart/values.yaml

* [monochart] Add `volumeClaimTemplates` to `StatefulSet`
* When you have an app which requires persistence, you should create a `StatefulSet` instead of `Deployment`. There are many benefits. You will not have to create a PVCs in advance, and you will be able to scale it easily. With the `StatefulSet`, you can define a `volumeClaimTemplates` so that a new PVC is created for each replica automatically. Also, you will end up with only one file which defines your app and also persistent volumes
* https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
* https://akomljen.com/kubernetes-persistent-volumes-with-deployment-and-statefulset/
* https://medium.com/@joatmon08/kubernetes-statefulset-recovery-from-aws-snapshots-8a6159cda6f1

[monochart] Add `volumeClaimTemplates` to `statefulset`

---

incubator/teleport-ent-proxy/Chart.yaml
incubator/teleport-ent-proxy/templates/NOTES.txt
incubator/teleport-ent-proxy/templates/certificate.yaml
incubator/teleport-ent-proxy/templates/deployment.yaml
incubator/teleport-ent-proxy/templates/service.yaml
incubator/teleport-ent-proxy/values.yaml

Enable private cluster which delegates access to other Trusted Teleport Cluster
Isolate cluster for better security (no direct access from internet)

[teleport-ent-proxy] Enable private cluster

---

incubator/cert-manager/.gitignore
incubator/cert-manager/.helmignore
incubator/cert-manager/Chart.yaml
incubator/cert-manager/README.md
incubator/cert-manager/cainjector/.helmignore
incubator/cert-manager/cainjector/Chart.yaml
incubator/cert-manager/cainjector/templates/_helpers.tpl
incubator/cert-manager/cainjector/templates/deployment.yaml
incubator/cert-manager/cainjector/templates/rbac.yaml
incubator/cert-manager/cainjector/templates/serviceaccount.yaml
incubator/cert-manager/cainjector/values.yaml
incubator/cert-manager/requirements.yaml
incubator/cert-manager/templates/NOTES.txt
incubator/cert-manager/templates/_helpers.tpl
incubator/cert-manager/templates/crds.yaml
incubator/cert-manager/templates/deployment.yaml
incubator/cert-manager/templates/rbac.yaml
incubator/cert-manager/templates/serviceaccount.yaml
incubator/cert-manager/values.yaml
incubator/cert-manager/webhook/.helmignore
incubator/cert-manager/webhook/Chart.yaml
incubator/cert-manager/webhook/templates/_helpers.tpl
incubator/cert-manager/webhook/templates/apiservice.yaml
incubator/cert-manager/webhook/templates/deployment.yaml
incubator/cert-manager/webhook/templates/pki.yaml
incubator/cert-manager/webhook/templates/rbac.yaml
incubator/cert-manager/webhook/templates/service.yaml
incubator/cert-manager/webhook/templates/serviceaccount.yaml
incubator/cert-manager/webhook/templates/validating-webhook.yaml
incubator/cert-manager/webhook/values.yaml

Create a chart for [`cert-manager`](https://github.com/jetstack/cert-manager/) that simply combines the official chart with the official Custom Resource Definitions.
- Eliminate the need to install the CRDs manually.
- Improve the usability of the chart with [`helmfile`](https://github.com/roboll/helmfile) by having `helm` directly manage the CRDs.

[cert-manager] Combine official chart with official Custom Resource Definitions

---

.dockerignore
incubator/teleport-ent-proxy/Chart.yaml
incubator/teleport-ent-proxy/templates/_helpers.tpl
incubator/teleport-ent-proxy/templates/clusterrole.yaml
incubator/teleport-ent-proxy/templates/clusterrolebinding.yaml
incubator/teleport-ent-proxy/templates/deployment.yaml
incubator/teleport-ent-proxy/templates/serviceaccount.yaml
incubator/teleport-ent-proxy/values.yaml

[teleport-ent-proxy] Satisfy RBAC requirements for Teleport v3.2
[Teleport v3.2](https://github.com/gravitational/teleport/releases/tag/v3.2.0) switched from using the CSR API on the auth server to using the impersonation API on the proxy server in order to grant access to Kubernetes resources. This requires new RBAC permissions for the proxy server.
https://github.com/gravitational/teleport/commit/aefe8860c108ab91a3836832e5013274a3353620#diff-98bdb67a508f59c119f00a0aaaeaef13
https://github.com/gravitational/teleport/blob/aefe8860c108ab91a3836832e5013274a3353620/examples/chart/teleport/templates/clusterrole.yaml

[teleport-ent-proxy] Satisfy RBAC requirements for Teleport v3.2

---

incubator/fluentd-kubernetes-aws/.helmignore
incubator/fluentd-kubernetes-aws/Chart.yaml
incubator/fluentd-kubernetes-aws/README.md
incubator/fluentd-kubernetes-aws/templates/NOTES.txt
incubator/fluentd-kubernetes-aws/templates/_helpers.tpl
incubator/fluentd-kubernetes-aws/templates/clusterrole.yaml
incubator/fluentd-kubernetes-aws/templates/clusterrolebinding.yaml
incubator/fluentd-kubernetes-aws/templates/daemonset.yaml
incubator/fluentd-kubernetes-aws/templates/prometheusrule.yaml
incubator/fluentd-kubernetes-aws/templates/service.yaml
incubator/fluentd-kubernetes-aws/templates/serviceaccount.yaml
incubator/fluentd-kubernetes-aws/templates/servicemonitor.yaml
incubator/fluentd-kubernetes-aws/values.yaml

A simplified chart for Fluentd with AWS Elasticsearch
- Add support for IAM role restrictions by signing requests to AWS Elasticsearch
- Add support for monitoring Fluentd with Prometheus via ServiceMonitor and PrometheusRules resources
- Add RBAC roles and bindings

[fluentd] Simplified chart for AWS elasticsearch

---

incubator/teleport-ent-auth/Chart.yaml
incubator/teleport-ent-auth/templates/deployment.yaml
incubator/teleport-ent-auth/values.yaml

1. Give longer time before failure is declared
1. Do not exit `bootstrap` script on failure
1. Typically takes about 60 seconds to come up on systems we have seen
1. Script is expected to encounter errors while server is starting

[teleport-ent-auth] Increase failure timeout length

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/service.yaml

* `ExternalName` service type support
* useful to create a gateway around SSO for external clients like SAAS

ExternalName service type supported now

---

incubator/nginx-default-backend/Chart.yaml
incubator/nginx-default-backend/templates/deployment.yaml
incubator/nginx-default-backend/templates/poddisruptionbudget.yaml
incubator/nginx-default-backend/values.yaml

[nginx-default-backend] Add a PodDisruptionBudget
Enable [nginx-default-backend] pods to be moved around during cluster scaling, etc.

[nginx-default-backend] Add a PodDisruptionBudget

---

incubator/teleport-ent-auth/Chart.yaml
incubator/teleport-ent-auth/templates/deployment.yaml
incubator/teleport-ent-auth/templates/poddisruptionbudget.yaml
incubator/teleport-ent-auth/values.yaml
incubator/teleport-ent-proxy/Chart.yaml
incubator/teleport-ent-proxy/templates/deployment.yaml
incubator/teleport-ent-proxy/templates/poddisruptionbudget.yaml
incubator/teleport-ent-proxy/values.yaml

- [teleport-ent-auth] Add PodDisruptionBudget
- [teleport-ent-proyx] Add PodDisruptionBudget and configurable pod annotations
- Better compatibility with cluster autoscaler

[teleport-ent-*] Add PodDisruptionBudgets to Teleport

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/_helpers.tpl
incubator/monochart/templates/deployment.yaml
incubator/monochart/values.example.yaml

* deployment support pod affinity and anti-affinity
* single simple `affinityRule` added - `ShouldBeOnDifferentNode`
* to be able to manage assigning pods to nodes
* to avoid repeating same common rules code in application chart values

deployment affinity support added

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/daemonset.yaml
incubator/monochart/templates/deployment.yaml
incubator/monochart/templates/service.yaml
incubator/monochart/templates/statefulset.yaml

* avoid accessing port when it is `null` in values
* having port as `null` in values will fail helm chart with `nil pointer evaluating interface`

fix to avoid accessing port fields when it is null

---

incubator/nginx-default-backend/Chart.yaml
incubator/nginx-default-backend/templates/deployment.yaml

* [nginx-default-backend] Add `selector` to `Deployment`
* Newer Kubernetes version require `selector` to be present in `DeploymentSpec`
* Otherwise, the following error is thrown:
```
failed processing release ingress-backend: helm exited with status 1:
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec
```
* https://stackoverflow.com/questions/59369174/unable-to-helm-install-due-to-deployment-manifest-issue

[nginx-default-backend] Add `selector` to `Deployment`

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/_helpers.tpl
incubator/monochart/values.example.yaml
incubator/monochart/values.yaml

* [monochart] Add `envFrom` section
* Allow converting existing Kubernetes secrets and config maps (without creating them) into ENV variables in pods that in turn can be accessed by the applications running in the pods
```
envFrom:
secrets: 
- secret-1
- secret-2
configMaps:
- config-1
- config-2
```

[monochart] Add `envFrom` section

---

incubator/monochart/templates/cronjob.yaml
incubator/monochart/templates/daemonset.yaml
incubator/monochart/templates/deployment.yaml
incubator/monochart/templates/job.yaml
incubator/monochart/templates/statefulset.yaml
incubator/monochart/values.example.yaml
incubator/monochart/values.yaml

* [monochart] Add `serviceAccountName` attribute
* To be able to provide an existing service account for pods (instead of using the default one)

[monochart] Add `serviceAccountName` attribute

---

incubator/fluentd-kubernetes-aws/templates/prometheusrule.yaml

* Reflect new metric names in alerts
* Added checks for absent metrics
* Change job to match `servicemonitor` configured
* Alerts were monitoring nonexistent metrics so they would never be triggered

[fluentd-kubernetes-aws] Change metrics names and improve alerts by introducing absent checks

---

incubator/fluentd-kubernetes-aws/templates/prometheusrule.yaml

* Revert changes done to alerting for fluentd
* Helm chart version wasn't updated which means that making diff can introduce unexpected changes
https://github.com/cloudposse/charts/pull/237

Revert changes to fluentd alerts

---

incubator/monochart/templates/cronjob.yaml
incubator/monochart/templates/daemonset.yaml
incubator/monochart/templates/deployment.yaml
incubator/monochart/templates/job.yaml
incubator/monochart/templates/statefulset.yaml

Using just `if .Values.serviceAccountName` requires it to be defined, even if you aren't using it.
This allows it to be missing if not required.
Not sure if this is your preferred way to do it.

Slightly better check for serviceAccountName's existence

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/cronjob.yaml
incubator/monochart/templates/ingress.yaml

- Update monochart so that it is compatible with k8s 1.16
- Beta APIs were promoted to non-beta

Update to k8s 1.16

---

.travis.yml

* Avoid calling `helm init` which is deprecated
* build-harness recently upgraded it's packages and this broke charts
* upstream build harness make target for `helm/install` is for helm2

Fix for Helm3

---

incubator/monochart/templates/_helpers.tpl

* Update `envFrom` section in `_helpers.tpl`
* `envFrom` is a list of `EnvFromSource` and there could be only one `envFrom` in a Container spec (possibly with many `configMapRef` and `secretRef` parameters)
* The current implementation creates two `envFrom` sections, which is not correct behavior and will fail if we use these two configs at the same time:
```
envFrom:
secrets:
- secret-1
configMaps:
- config-1
```
and 
```
secrets:
default:
enabled: true
mountPath: /secret-default
annotations:
test.secret.annotation: value
labels:
test_label: value
env:
SECRET_ENV_NAME: ENV_VALUE
files:
secret.test.txt: |-
some text
```
* This update puts all `configMapRef` and `secretRef` parameters into just one `envFrom`  section

[monochart] Update `envFrom`

---

incubator/cert-manager/Chart.yaml

- Deprecate cert-manager chart
- Per [request](https://github.com/helm/hub/issues/402#issuecomment-659404818) prior to deleting the chart, as outlined in [Helm documentation](https://helm.sh/docs/topics/charts/#deprecating-charts)
- Prerequisite to #252

[cert-manager] Deprecate chart

---

incubator/fluentd-kubernetes-aws/Chart.yaml
incubator/fluentd-kubernetes-aws/templates/daemonset.yaml

- [fluentd-kubernetes-aws] Fix syntax error
- Chart would fail if environment variables were set

[fluentd-kubernetes-aws] Fix syntax error

---

incubator/monochart/Chart.yaml
incubator/monochart/requirements.yaml
incubator/monochart/templates/_common_fullname.tpl
incubator/monochart/templates/_common_metadata_labels.tpl
incubator/monochart/templates/_common_name.tpl
incubator/monochart/templates/job.yaml
incubator/monochart/values.yaml

In [monochart]:
- Fix incorrect reference to `serviceAccount` in `jobs.yaml`
- Use empty maps rather than `nil` for default empty map values
- Remove dependency on obsolescent Kubernetes incubator Helm repo by copying needed templates
- Caused error when defining a job
- Caused unnecessary warning messages
- Repo scheduled to be marked obsolete on Nov 13, 2020

[monochart] Fix bugs, remove dependency on obsolescent Kubernetes repo

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/cronjob.yaml

When not defined, the cronjob fails in helm with:
```
Error: Failed to render chart: exit status 1: Error: template: monochart/templates/cronjob.yaml:40:7: executing "monochart/templates/cronjob.yaml"
at <index .Values "serviceAccountName">: error calling index: index of untyped nil     
```
This should fix that.

Fixes bad check for serviceAccountName

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/deployment.yaml
incubator/monochart/templates/statefulset.yaml
incubator/monochart/values.yaml

Changes to [monochart]
- Make StatefulSet.terminationGracePeriod configurable
- Make persistence optional for Deployments and StatefulSets
- Fix pod labels in StatefulSets
- Add podAffinity/podAntiAffinity options to StatefulSets
- Was not configurable and was set to zero, which is explicitly discouraged in Kubernetes documentation (now defaults to 10)
- Deployments used `emptyDir` storage by default, which make the Cluster AutoScaler unwilling to move them. StatefulSets required a PersistentVolume even though not strictly required.
- Indentation error broke pod labels for StatefulSets
- StatefulSets benefit from podAntiAffinity even more than Deployments do

[monochart] make persistence optional, fix SS labels

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/_helpers.tpl
incubator/monochart/values.example.yaml
incubator/monochart/values.yaml

* [monochart] Add `envFromFieldRefFieldPath` config
* To be able to declare ENV vars from pod fields
* Example usage is Datadog APM to declare dynamic ENV var `DD_AGENT_HOST` from pod field `status.hostIP`
* https://docs.datadoghq.com/agent/kubernetes/apm/?tab=helm
* https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables

[monochart] Add `envFromFieldRefFieldPath` config

---

incubator/monochart/values.yaml

* Remove port default values 
* Whilst this is a good default it makes it hard to add your own custom name, as port duplication is possible

monochart default ports

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/_helpers.tpl
incubator/monochart/values.example.yaml
incubator/monochart/values.yaml

Adds the ability to use the `secretKeyRef` style of adding environment variables to kubernetes specs.
While this is already provided via `envFrom` in this chart, and the corresponding kubernetes features, envFrom doesn't allow you to specify the target environment variable name in your pods, nor does it allow you to use keys in your secrets that aren't valid environment variable names.
* https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
Providing this value:
```yaml
envFromSecretKeyRef:
- name: CELERY_BROKER_USERNAME
secret: example-rabbitmq-default-user
key: username
- name: CELERY_BROKER_PASSWORD
secret: example-rabbitmq-default-user
key: password
```
Would add the following to the template:
```yaml
env:
- name: CELERY_BROKER_USERNAME …
```

Adds ability to use secretKeyRef in env spec

---

.github/workflows/charts.yml

Update github output syntax
Following github docs
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Update github output syntax

---

incubator/monochart/templates/_helpers.tpl
incubator/monochart/templates/deployment.yaml
incubator/monochart/test/full.yaml
incubator/monochart/values.yaml

This reverts commit 61ffa1b0f67e3e6e6efe4e9def6bed2337b11e06.
* I Merged a PR #273 without updating Chart.yaml
* Versioning isn't automatic, we don't want to override 0.26.0

Revert "`[Monochart]` Feature: `deployment.yaml` volume mounts (#273)"
