cloudposse/charts

README.md

* Add TravisCI Build Status Badge
* transparency

Add TravisCI Build Status Badge

---

incubator/bastion/Chart.yaml
incubator/bastion/values.yaml

* Update `values.yaml` to use default settings for `sudosh`
* Using `sudosh` is recommended

Default to Using Sudosh on Bastion

---

incubator/openvpn/templates/vpn.deployment.yaml
incubator/openvpn/values.yaml

* Replace `dhcp-option DOMAIN-SEARCH` with `dhcp-option DOMAIN` 
* Support custom search domains in `values.yaml`
* `dhcp-option DOMAIN` seems to be more widely supported by OpenVPN clients like viscosity

Improve DHCP DNS Search Domain

---

incubator/kube-lego/Chart.yaml
incubator/kube-lego/templates/deployment.yaml
incubator/kube-lego/values.yaml

* Added kube-lego debug option
* Facilitate debugging for development purposes; not recommended for production

Added debug option for kube-lego

---

incubator/nfs-provisioner/Chart.yaml
incubator/nfs-provisioner/templates/statefulset.yaml
incubator/nfs-provisioner/values.yaml

* Provide way to mount hostPath
*  This is useful on GCE because by default they provide 100Gb and I want to utilize them
@osterman

Add Support for Multiple Volume Types

---

incubator/grafana/Chart.yaml
incubator/grafana/README.md
incubator/grafana/templates/NOTES.txt
incubator/grafana/templates/_helpers.tpl
incubator/grafana/templates/configmap.yaml
incubator/grafana/templates/dashboards-configmap.yaml
incubator/grafana/templates/deployment.yaml
incubator/grafana/templates/ingress.yaml
incubator/grafana/templates/job.yaml
incubator/grafana/templates/pvc.yaml
incubator/grafana/templates/secret.yaml
incubator/grafana/templates/svc.yaml
incubator/grafana/values.yaml

* Forked from https://github.com/kubernetes/charts/tree/master/stable/grafana

Fork of Grafana from Official Kubernetes Stable Charts

---

incubator/exporter-kube-dns/.helmignore
incubator/exporter-kube-dns/Chart.yaml
incubator/exporter-kube-dns/templates/_helpers.tpl
incubator/exporter-kube-dns/templates/service.yaml
incubator/exporter-kube-dns/templates/servicemonitor.yaml
incubator/exporter-kube-dns/values.yaml

* Created chart that provide prometheus exporter kube dns and alerts for it

Added prometheus exporter kube dns

---

incubator/exporter-node/.helmignore
incubator/exporter-node/Chart.yaml
incubator/exporter-node/templates/NOTES.txt
incubator/exporter-node/templates/_helpers.tpl
incubator/exporter-node/templates/configmap.yaml
incubator/exporter-node/templates/deamonset.yaml
incubator/exporter-node/templates/service.yaml
incubator/exporter-node/templates/servicemonitor.yaml
incubator/exporter-node/values.yaml

* Created chart that provide prometheus exporter node and alerts for it

Added prometheus exporter node

---

incubator/exporter-kubernetes/.helmignore
incubator/exporter-kubernetes/Chart.yaml
incubator/exporter-kubernetes/templates/_helpers.tpl
incubator/exporter-kubernetes/templates/configmap.yaml
incubator/exporter-kubernetes/templates/servicemonitor.yaml
incubator/exporter-kubernetes/values.yaml

* Created chart that provide prometheus exporter kubernetes and alerts for it

Added prometheus exporter kubernetes

---

incubator/exporter-kube-api/.helmignore
incubator/exporter-kube-api/Chart.yaml
incubator/exporter-kube-api/templates/_helpers.tpl
incubator/exporter-kube-api/templates/configmap.yaml
incubator/exporter-kube-api/templates/service.yaml
incubator/exporter-kube-api/templates/servicemonitor.yaml
incubator/exporter-kube-api/values.yaml

* Created chart that provide prometheus exporter kube api and alerts for it

Added prometheus exporter kube api

---

incubator/exporter-kube-controller-manager/.helmignore
incubator/exporter-kube-controller-manager/Chart.yaml
incubator/exporter-kube-controller-manager/templates/_helpers.tpl
incubator/exporter-kube-controller-manager/templates/configmap.yaml
incubator/exporter-kube-controller-manager/templates/service.yaml
incubator/exporter-kube-controller-manager/templates/servicemonitor.yaml
incubator/exporter-kube-controller-manager/values.yaml

* Created chart that provide prometheus exporter kube controller manager and alerts for it

Added prometheus exporter kube controller manager

---

incubator/exporter-kube-etcd/.helmignore
incubator/exporter-kube-etcd/Chart.yaml
incubator/exporter-kube-etcd/templates/_helpers.tpl
incubator/exporter-kube-etcd/templates/configmap.yaml
incubator/exporter-kube-etcd/templates/service.yaml
incubator/exporter-kube-etcd/templates/servicemonitor.yaml
incubator/exporter-kube-etcd/values.yaml

* Created chart that provide prometheus exporter kube etcd and alerts for it

Added prometheus exporter kube etcd

---

incubator/exporter-kube-scheduler/.helmignore
incubator/exporter-kube-scheduler/Chart.yaml
incubator/exporter-kube-scheduler/templates/_helpers.tpl
incubator/exporter-kube-scheduler/templates/configmap.yaml
incubator/exporter-kube-scheduler/templates/service.yaml
incubator/exporter-kube-scheduler/templates/servicemonitor.yaml
incubator/exporter-kube-scheduler/values.yaml

* Created chart that provide prometheus exporter kube scheduler and alerts for it

Added prometheus exporter kube scheduler

---

incubator/exporter-kubelets/.helmignore
incubator/exporter-kubelets/Chart.yaml
incubator/exporter-kubelets/templates/_helpers.tpl
incubator/exporter-kubelets/templates/configmap.yaml
incubator/exporter-kubelets/templates/servicemonitor.yaml
incubator/exporter-kubelets/values.yaml

* Created chart that provide prometheus exporter kubelets and alerts for it

Added prometheus exporter kubelets

---

incubator/kube-prometheus/requirements.yaml

* Remove exporter-kube-state from kube-prometheus deps
* There is something with CI\CD need to debug

Fix charts CI\CD

---

incubator/prometheus/Chart.yaml
incubator/prometheus/templates/servicemonitors.yaml

* Fixed service Monitors list
* Service monitors specified in yaml is one of use cases

Fix bug in service monitor list

---

incubator/kube-prometheus/values.yaml

* Added slack notifier config to values.yaml
* We want to have alerts with slack

Added slack notifications

---

incubator/prometheus-alerts/templates/configmap.yaml
incubator/prometheus-alerts/values.yaml

* Added metric pod often restart
* Added alert on pod often restart
* If pod often restarts this is error

Define Alert/Metric for Pod Restarts per Hour

---

incubator/prometheus-alerts/templates/configmap.yaml
incubator/prometheus-alerts/values.yaml

* Added metric cluster memory free %
* Added alert on low cluster memory free %
* Cluster memory measure is very important

Added metric cluster free memory

---

incubator/openvpn/templates/vpn.configmap.yaml
incubator/openvpn/templates/vpn.deployment.yaml
incubator/openvpn/values.yaml

* Split TTL setting for client and server certs
*  Client certificates should expire earlier then server certificate

[openvpn] Split TTL for Server cert and Client cert

---

incubator/jenkins/Chart.yaml
incubator/jenkins/templates/ingress.yaml
incubator/jenkins/values.yaml
incubator/lamp/Chart.yaml
incubator/lamp/templates/ingress.yaml
incubator/lamp/values.yaml

* Added way to define custom annotations to ingress in lamp and jenkins charts
* Annotations for ingress provide a way to change nginx params.

Added ingress annotations for jenkins and lamp ingress

---

incubator/fail-whale/Chart.yaml
incubator/fail-whale/templates/deployment.yaml
incubator/jenkins/Chart.yaml
incubator/jenkins/templates/jenkins-master-deployment.yaml
incubator/kube-lego/Chart.yaml
incubator/kube-lego/templates/deployment.yaml
incubator/nginx-default-backend/Chart.yaml
incubator/nginx-default-backend/templates/deployment.yaml
incubator/nginx-ingress/Chart.yaml
incubator/nginx-ingress/templates/deployment.yaml
incubator/oauth2-proxy/Chart.yaml
incubator/oauth2-proxy/templates/deployment.yaml
incubator/openvpn/Chart.yaml
incubator/openvpn/templates/vpn.deployment.yaml
incubator/postfix/Chart.yaml
incubator/postfix/templates/deployment.yaml
incubator/remotecv/Chart.yaml
incubator/remotecv/templates/deployment.yaml
incubator/varnish/Chart.yaml
incubator/varnish/templates/deployment.yaml
incubator/vps/Chart.yaml
incubator/vps/templates/deployment.yaml

* Changed way how auto rolling updates configured for new versions of helm
* Recommendations how automatically roll deployments when config maps or secrets change  https://docs.helm.sh/developing_charts/#chart-development-tips-and-tricks
* https://github.com/cloudposse/charts/issues/121

Fixed auto rolling deploymnents

---

incubator/chart-repo/.helmignore
incubator/chart-repo/Chart.yaml
incubator/chart-repo/LICENSE
incubator/chart-repo/README.md
incubator/chart-repo/requirements.yaml
incubator/chart-repo/templates/NOTES.txt
incubator/chart-repo/values.yaml

* Umbrella chart for chartmuseum.
* Use one chartmuseum subchart to serve
* Use second chartmuseum subchart as push gateway
* Allow to make private repo with different access to pull and to push
* Based on official chartmuseum

Added chart repo

---

incubator/chart-repo/Chart.yaml
incubator/chart-repo/values.yaml
incubator/oauth2-proxy/Chart.yaml
incubator/oauth2-proxy/templates/ingress.yaml

* Fix chart repo default values
* Fix Ingress for oauth2-proxy
* Values was messed between server and api gateway
* Ingress was broken

Fix chart-repo and oauth2-proxy charts

---

incubator/oauth2-proxy/Chart.yaml
incubator/oauth2-proxy/templates/configmap.yaml
incubator/oauth2-proxy/templates/ingress.yaml
incubator/oauth2-proxy/values.yaml

* Use oauth2 version 2.2
* Disable auth by login\password if app.htpasswdFile value is empty
* Fix Ingress port
* It supports X-Auth-Request-Redirect header
* Provide way to disable simple login\password auth form
* Allow to create ingress specifying propriate values in values.yaml

Enhancements for oauth2-proxy

---

incubator/chart-repo/Chart.yaml
incubator/chart-repo/requirements.yaml
incubator/chart-repo/values.yaml

* Use new version of chartmuseum
* It support  configuration of probes

Update version for chart museum

---

incubator/chart-repo/Chart.yaml
incubator/chart-repo/values.yaml

* Fix probe
* Mistype for probe values

Fix probes

---

.travis.yml
Makefile
incubator/dockercfg/.helmignore
incubator/dockercfg/Chart.yaml
incubator/dockercfg/requirements.yaml
incubator/dockercfg/templates/NOTES.txt
incubator/dockercfg/templates/secret.yaml
incubator/dockercfg/values.yaml

* Deploy a `dockercfg` secret to a namespace
* Useful to support other charts that require a `pullSecret`

Add dockercfg chart

---

incubator/fluentd-kubernetes/Chart.yaml
incubator/fluentd-kubernetes/templates/daemonset.yaml

* Disable read-only for logs volumes
* Added tolerance for master nodes
* Allow fluentd to store `*.pos` files in logs dir
* Collect logs on masters

Feature fix fluentd chart

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/_helpers.tpl
incubator/monochart/templates/daemonset.yaml
incubator/monochart/templates/deployment.yaml
incubator/monochart/templates/job.yaml
incubator/monochart/templates/statefulset.yaml
incubator/monochart/values.example.yaml
incubator/monochart/values.yaml

* fix container args
* improve env template
* make configMap/secret mountPath configurable

[incubator/monochart]: improvements and fixes

---

incubator/teleport/.helmignore
incubator/teleport/Chart.yaml
incubator/teleport/Makefile
incubator/teleport/README.md
incubator/teleport/templates/_helpers.tpl
incubator/teleport/templates/clusterrole.yaml
incubator/teleport/templates/clusterrolebinding.yaml
incubator/teleport/templates/config.yaml
incubator/teleport/templates/deployment.yaml
incubator/teleport/templates/ingress.yaml
incubator/teleport/templates/service.yaml
incubator/teleport/templates/serviceaccount.yaml
incubator/teleport/values.yaml

import teleport chart
teleport doesn't have any hosted charts
https://github.com/cloudposse/helmfiles/issues/35

[incubator/teleport]: import chart

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/cronjob.yaml
incubator/monochart/templates/ingress.yaml
incubator/monochart/templates/job.yaml
incubator/monochart/values.yaml

* Added `CronJob` resource
* Fix `Job` resource
* Fix `Ingress` resource
* To support more complex apps

[monochart] add support for `CronJobs`

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/_helpers.tpl
incubator/monochart/templates/daemonset.yaml
incubator/monochart/templates/deployment.yaml
incubator/monochart/templates/statefulset.yaml
incubator/monochart/values.yaml

* Fix resources
* Fix healthcheck
* Fix env vars
* Disable probes by default
* To use monochart

[monochart] Fix formatting, disable probes by default

---

incubator/openvpn/README.md
incubator/route53-kubernetes/README.md

fix incorrect URLs in examples
#176

[docs]: fix incubator repo url

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/_helpers.tpl
incubator/monochart/templates/configmap.yaml
incubator/monochart/templates/daemonset.yaml
incubator/monochart/templates/deployment.yaml
incubator/monochart/templates/job.yaml
incubator/monochart/templates/secret.yaml
incubator/monochart/templates/statefulset.yaml

* Do not deploy secrets if none defined
* We ran into problems where a service expected only one secret with a particular label to be deployed (cloudflare argo-ingress)

Monochart fix secrets

---

incubator/bastion/Chart.yaml
incubator/bastion/templates/deployment.yaml

Init container annotations seem to no longer work and cause deployment of bastion via helm to fail.

Fix init-container

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/ingress.yaml
incubator/monochart/values.yaml

* Made ingress port configurable
* To define multiple ingresses for different ports

Monochart support ingress port configure

---

incubator/monochart/Chart.yaml
incubator/monochart/values.yaml

* Disable resources request/limit by default
* Allow developers to manage QoS classes https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/resource-qos.md#qos-classes

[monochart] Remove resources by default

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/deployment.yaml

Fix handling of deployment `command` and `args` parameters
Chart was generating invalid YAML unless command and arg were empty or just one token

[monochart] Fix deployment command and arg handling

---

incubator/superset/.helmignore
incubator/superset/Chart.yaml
incubator/superset/README.md
incubator/superset/templates/NOTES.txt
incubator/superset/templates/_helpers.tpl
incubator/superset/templates/deployment.yaml
incubator/superset/templates/ingress.yaml
incubator/superset/templates/pvc.yaml
incubator/superset/templates/secret.yaml
incubator/superset/templates/svc.yaml
incubator/superset/templates/workers.yaml
incubator/superset/values.yaml

* improved superset chart ([source](https://github.com/helm/charts/tree/master/stable/superset))
* we need worker as well as server for superset
* Supported only one worker replica (with configurable concurrency). For more replicas, we need to add support `celery beat`

[incubator/superset] Superset chart

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/cronjob.yaml
incubator/monochart/templates/job.yaml

[monochart] Fix job and cronjob handling of command and args
Chart previously generated invalid YAML in certain situations

[monochart] Fix job and cronjob handling of command and args

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/_istio_helpers.tpl
incubator/monochart/templates/istio-virtualservices.yaml
incubator/monochart/test/full.yaml
incubator/monochart/values.yaml

* Added Istio VirtualService
* To support Istio

[monochart] Added Istio

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/crd.yaml

[monochart] Fix monochart crd

---

Makefile
incubator/monochart/Chart.yaml
incubator/monochart/templates/service.yaml

* specify selectors for service definition or use a default
* there are times when one wants to choose their own selectors for a service

Allow Service Default to be overriden

---

incubator/superset/Chart.yaml
incubator/superset/templates/workers.yaml
incubator/superset/values.yaml

* [superset] workers resources now cut of web resources
* to be able to set different resources values for web and for workers

split resources for superset web and workers

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/_helpers.tpl

* [monochart] Update `envFrom` section
* Fix formatting. The generated YAML looked like this before:
```
env:
+         envFrom:- secretRef:
+             name: GOCAL_SECRET_1
```
* Missed the conditional check and `envFrom` attribute
```
{{- if $root.Values.envFrom }}
envFrom:
```

[monochart] Update `envFrom` section

---

incubator/monochart/Chart.yaml

* [monochart] Update chart version
* New features were added in the previous PR, but the chart version was not updated
* https://github.com/cloudposse/charts/pull/235

[monochart] Update chart version

---

incubator/superset/Chart.yaml
incubator/superset/templates/deployment.yaml
incubator/superset/values.yaml

upgrade superset to 0.35.2

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/daemonset.yaml
incubator/monochart/templates/deployment.yaml
incubator/monochart/templates/statefulset.yaml

* Update monochart k8s resources API
* Legacy API deprecated in new k8s versions

[monochart] Fix resources API

---

.github/workflows/charts.yml
Makefile
incubator/Makefile
incubator/chart-repo/requirements.yaml
incubator/codefresh-service-account/requirements.yaml
incubator/monochart/Chart.yaml
incubator/monochart/templates/ingress.yaml
incubator/monochart/values.yaml
incubator/portal/requirements.yaml
test/Makefile

* Support K8s version 1.22
* Different versions of k8s use different structure for Ingress resources

[monochart] Support K8S version 1.22

---

incubator/monochart/templates/_helpers.tpl
incubator/monochart/templates/deployment.yaml
incubator/monochart/test/full.yaml
incubator/monochart/values.yaml

* Feature volumes and mounts
* Bugfix: duplicate env block
* Bugfix: empty image-pull-secrets
* Bugfix: empty volume blocks
* Allows volume mounts in deployment
* Bugfixes
* `helmfile template render`

`[Monochart]` Feature: `deployment.yaml` volume mounts

---

incubator/monochart/Chart.yaml
incubator/monochart/templates/_helpers.tpl
incubator/monochart/templates/deployment.yaml
incubator/monochart/test/full.yaml
incubator/monochart/values.yaml

* Feature volumes and mounts
* Bugfix: duplicate env block
* Bugfix: empty image-pull-secrets
* Bugfix: empty volume blocks
* Allows volume mounts in deployment
* Bugfixes
* `helmfile template render`

`[Monochart 0.27.0]` Feature: `deployment.yaml` volume mounts
